# Generated by Django 5.0.7 on 2024-07-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='daily_rent_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
