# Generated by Django 5.0.7 on 2024-07-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_alter_product_daily_rent_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(max_length=100),
        ),
    ]
